---
fail_fast: false
default_language_version:
    python: python3.10
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.17
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-gfm
                - mdformat-black
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck
            args: [--severity=error]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            # Use mypy installed in the system rather than in pre-commit's env to check PyTorch types.
            language: system
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.3
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
          # - id: clang-tidy # No easy way to install clang-tidy on macOS
          # - id: oclint # oclint uses dylds that were not verified by macOS
          # - id: uncrustify # seems conflicts with clang-format
          # - id: cppcheck # No cppcheck on RedHat Linux
          - id: cpplint
          # - id: include-what-you-use # Cannot handle including files from external frameworks
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v17.0.6
      hooks:
          - id: clang-format
            args: [--style=Google, -i]
